### ISSUE TITLE
Fix macOS build

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#130]
See https://github.com/neopostmodern/wohnungsbot/actions/runs/3731576364/jobs/6329968056
```
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/runner/work/wohnungsbot/wohnungsbot/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:410:5)
    at ChildProcess.errorhandler (node:child_process:422:5)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
  • Above command failed, retrying 5 more times
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • Above command failed, retrying 0 more times
  • building block map  blockMapFile=release/Wohnungsbot-1.6.0-mac.zip.blockmap
/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
				^

Error: Command failed: npx --no-install electron-builder --mac  -p never
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at run (/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:132:4)
    at Object.<anonymous> (/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8839,
  stdout: null,
  stderr: null
}
```

**Comment by drblaui** [comment]
Seems like [upgrading electron builder](https://github.com/electron-userland/electron-builder/issues/6726) might help

**Comment by neopostmodern** [comment]
@drblaui that was easy :)
