### ISSUE TITLE
logout doesn't work

### ISSUE THREAD

**Issue by geohiehoe** [neopostmodern/wohnungsbot#148]
recreate with:
- use login "yes" and provide your data
- start the bot (will log you in)
- go back to settings and say "use login no"
- start the bot (will try to log you out)

error pops up multiple times:
```
isElementInViewport(.topnavigation__overlay--account) called on non-existent element
Error executing JavaScript-snippet within webContents:
[TypeError] Cannot read properties of null (reading 'scrollIntoView')
TypeError: Cannot read properties of null (reading 'scrollIntoView')
    at <anonymous>:3:77
    at new Promise (<anonymous>)
    at <anonymous>:1:1

This is the code that caused the error:
new Promise((resolve, reject) => {
       try {
          resolve(document.querySelector('.topnavigation__overlay--account').scrollIntoView({ behavior: 'smooth', block: 'nearest'}))
       } catch(err) {
          throw { name: err.name, message: err.message, stack: err.stack }
       }
    })
// END OF CODE

Stack that led to the execution of this snippet (Electron):
 at shadowRootSelector (/home/georg/Mega/Projekte/wohnungsbot/wohnungsbot/app/webpack:/wohnungsbot/app/actions/botHelpers.js:154:25)
 at focus (/home/georg/Mega/Projekte/wohnungsbot/wohnungsbot/app/webpack:/wohnungsbot/app/actions/botHelpers.js:219:7)
 at resumeValue (/home/georg/Mega/Projekte/wohnungsbot/wohnungsbot/app/webpack:/wohnungsbot/app/actions/botHelpers.js:32:19)
 at promiseReturnValue (/home/georg/Mega/Projekte/wohnungsbot/wohnungsbot/app/webpack:/wohnungsbot/app/utils/generators.js:19:9)
 at /home/georg/Mega/Projekte/wohnungsbot/wohnungsbot/app/webpack:/wohnungsbot/app/utils/async.js:12:13

```

**Comment by geohiehoe** [comment]
- I wonder why the error pop's up multiple times. 
- It would be interesting to have some error recovery, and show the user in the window "unexpected error happened"

**Comment by geohiehoe** [comment]
First draft is solving this by calling 'https://sso.immobilienscout24.de/sso/logout?sso_return=https://www.immobilienscout24.de'

Other option would be to navigate to 'https://www.immobilienscout24.de/geschlossenerbereich/start.html?source=headericon' (as done for logging in) and then click 'Abmelden' at the bottom

**Comment by geohiehoe** [comment]
minor remaining thing: the bot message "Abmelden" gets interrupted two times and then "Website lädt..." appears. Might be technically correct, but just by appearance its looks flaky
